#!/bin/bash

# setup_keys
#
# Generate SSH keys for Ansible communication.
#

while getopts "i:" opt
do
  case $opt in
    i) _RSAKeyFile=${OPTARG}
       ;;
    *) /usr/bin/printf "Invalid arguments\n"
       exit 1
  esac

done

if [ "${_RSAKeyFile}" == "" ]
then
  /usr/bin/printf "No hostfile specified\n"
  exit 1
fi

if [ ! -e "${_RSAKeyFile}" ]
then
  /usr/bin/printf "Hostfile %s does not exist.\n" "${_RSAKeyFile}"
  exit 1
fi

# Go to script directory.
cd $(dirname ${0})
cd ..

# Derive the relative path to the Inventory file based on the current directory.
_InventoryFile=$(pwd)/hosts

# Function to generate new id_rsa keyfile.
function generateKeyfile
{
  /usr/bin/ssh-keygen -b 8192 -N '' -C "Ansible Key"

  return ${?}
}

# If the RSA Keyfile does not exist, call the function to create the file.
if [ ! -f ${_RSAKeyFile} ]
then
  ls -l  ${_RSAKeyFile}
  generateKeyFile
fi

# Parse the list of Ansibl hosts and copy the id_rsa SSH key.
/usr/bin/ansible all -i ${_InventoryFile} --list-hosts | \
while read input
do

  cat <<_EOD_
  Working on host ${input}
_EOD_

  /usr/bin/ssh-copy-id -i ${HOME}/.ssh/id_rsa ${input}

done

exit 0
